"""Typed nbformat I/O subset whose upstream functions lack annotations.

Upstream: nbformat/__init__.py and nbformat/notebooknode.py.
"""

class NotebookNode(dict[str, object]): ...

def read(fp: str, as_version: int) -> NotebookNode: ...
def write(nb: NotebookNode, fp: str) -> None: ...
def validate(nbdict: NotebookNode) -> None: ...
